name: Build
on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version:
                    - 8.1

        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}

            -   uses: actions/checkout@v2

            -   name: Cache Composer packages
                if: ${{ !env.ACT }}
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install Dependencies
                run: composer update -q --no-ansi --no-interaction --no-progress

            -   name: Run static analysis
                run: composer run-script analyse

            -   name: Execute tests (Unit tests) via PHPUnit
                env:
                    SYMFONY_DEPRECATIONS_HELPER: 'max[direct]=0'
                run: composer run-script test
