name: Local build
on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    build:
        if: ${{ github.event.act }}
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_USER: symandy
                    MYSQL_PASSWORD: symandy
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: db_test_1
                ports:
                    - 52000:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        strategy:
            matrix:
                php-version:
#                    - 8.1
                    - 8.2 # Cannot run both version in parallel as creating database on the second one fails (already exists)

        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}

            -   uses: actions/checkout@v3

            -   name: Install Dependencies
                run: composer update -q --no-ansi --no-interaction --no-progress

            -   name: Run static analysis
                run: composer run-script analyse

#            -   name: Mysql Dump
#                run: MYSQL_PWD=root mysqldump -u root -h 172.17.0.2 -P 3306 --databases db_test_1 > db_test_1.sql

            -   name: Execute tests (Unit tests) via PHPUnit
                env:
                    SYMFONY_DEPRECATIONS_HELPER: 'max[direct]=0'
                    TEST_DATABASE_USER: root
                    TEST_DATABASE_PASSWORD: root
                    TEST_DATABASE_HOST: 172.17.0.2
                    TEST_DATABASE_PORT: 3306
                    TEST_DATABASE_NAME: db_test_1
                run: composer run-script test
